=== DreadPirateRoberts-1000/wdb-netcdfload/etc/netcdfLoad.configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="dimension_type">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="netcdf_type">
		<xs:sequence>
			<xs:element name="dimension" type="dimension_type"
				minOccurs="0" maxOccurs="1" />  <!-- update to unbounded once many extra dimensions are supported -->
		</xs:sequence>
		<xs:attribute name="cfname" type="xs:string" use="required" />
		<!-- It should be mandatory to use on of these, instead of cfname:
			<xs:attribute name="variable_name" type="xs:string" use="optional" />
			<xs:attribute name="standard_name" type="xs:string" use="optional" />
		 -->
	</xs:complexType>

	<xs:complexType name="level_type">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:double" use="optional" default="0" />
	</xs:complexType>

	<xs:complexType name="wdb_type">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="scale" type="xs:float" use="optional" />
		<!-- 
		Validfrom can be one of the special values "validtime" or 
		"referencetime". You may add or subtract a fixed amount of hours from 
		this selection, such as this: "validtime - 6 hours".
		-->
		<xs:attribute name="validfrom" type="xs:string" use="optional" default="validtime" />
		<!-- <xs:attribute name="validto" type="xs:string" use="optional" default="validtime" /> -->

		<xs:sequence>
			<xs:element name="level" type="level_type"
				minOccurs="" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="load_type">
		<xs:sequence>
			<xs:element name="netcdf" type="netcdf_type"/>
			<xs:element name="wdb" type="wdb_type"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="netcdfloadconfiguration_type">
		<xs:sequence>
			<xs:element name="load" type="load_type"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="netcdfloadconfiguration" type="netcdfloadconfiguration_type" />

</xs:schema>

=== DreadPirateRoberts-1000/wdb-netcdfload/etc/vega.netcdfload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

	<!--
	<load>
		<netcdf variable_name="altitude" />
		<wdb name="altitude" units="m" validfrom="-infinity" validto="infinity"/>
	</load>
	-->

	<load>
		<netcdf variable_name="lwe_thickness_of_precipitation_amount"/>
		<wdb name="precipitation amount" units="kg/m2" alternativeunitconversion="mm" validfrom="referencetime"/>
	</load>
	<load>
		<netcdf variable_name="precipitation_amount"/>
		<wdb name="precipitation amount" units="kg/m2" alternativeunitconversion="mm" validfrom="referencetime"/>
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction"/>
		<wdb name="cloud area fraction" units="%"/>
	</load>
	<load>
		<netcdf variable_name="air_temperature"/>
		<wdb name="air temperature" units="K">
			<level name="height above ground" value="2" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="relative_humidity"/>
		<wdb name="relative humidity" units="%" >
			<level name="height above ground" value="2" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="wind_speed" />
		<wdb name="wind speed" units="m/s">
			<level name="height above ground" value="10" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="wind_from_direction"/>
		<wdb name="wind from direction" units="rad" alternativeunitconversion="m/s">
			<level name="height above ground" value="10" />
		</wdb>
	</load>

	<!-- 	
	<load>
		<netcdf variable_name="x_wind_10m"/>
		<wdb name="x wind" units="m/s">
			<level name="height above ground" value="10" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="y_wind_10m"/>
		<wdb name="y wind" units="m/s">
			<level name="height above ground" value="10" />
		</wdb>
	</load>
	-->

	<load>
		<netcdf variable_name="cloud_area_fraction_in_atmosphere_layer">
			<dimension name="sigma" value="1000" />
		</netcdf>
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="1000"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction_in_atmosphere_layer">
			<dimension name="sigma" value="300" />
		</netcdf>
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="300"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction_in_atmosphere_layer">
			<dimension name="sigma" value="500" />
		</netcdf>
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="500"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction_in_atmosphere_layer">
			<dimension name="sigma" value="850" />
		</netcdf>
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="850"/>
		</wdb>
	</load>

	<load>
		<netcdf variable_name="sea_level_pressure"/>
		<wdb name="air pressure at sea level" units="Pa"/>
	</load>

	<conversions>
		<vector x="x_wind_10m" y="y_wind_10m">
			<speed name="wind_speed" />
			<direction name="wind_from_direction" />
		</vector>
	</conversions>
	
</netcdfloadconfiguration>

=== DreadPirateRoberts-1000/wdb-netcdfload/test/data/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

	<load>
		<netcdf variable_name="air_temperature_2m" />
		<wdb name="air temperature" units="K"/>
	</load>

	<load>
		<netcdf variable_name="precipitation_amount"/>
		<wdb name="lwe thickness of precipitation amount" units="kg/m2" validfrom="validtime - 6 hours"/>
	</load>

	<load>
		<netcdf variable_name="cloud_area_fraction">
			<dimension name="percentile" value="0.1" />
		</netcdf>
		<wdb name="10th percentile of cloud area fraction" units="K" />
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction">
			<dimension name="percentile" value="0.25" />
		</netcdf>
		<wdb name="25th percentile of cloud area fraction" units="K" />
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction">
			<dimension name="percentile" value="0.5" />
		</netcdf>
		<wdb name="50th percentile of cloud area fraction" units="K" />
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction">
			<dimension name="percentile" value="0.75" />
		</netcdf>
		<wdb name="75th percentile of cloud area fraction" units="K" />
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction">
			<dimension name="percentile" value="0.9" />
		</netcdf>
		<wdb name="90th percentile of cloud area fraction" units="K" />
	</load>
	

</netcdfloadconfiguration>

=== DreadPirateRoberts-1000/wdb-netcdfload/etc/oceanforecast.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

	<!-- KEEP THIS ALPHABETICALLY ORDERED ON NETCDF VARIABLE NAME! -->
	<load>
	  <netcdf variable_name="aice"/>
	  <wdb name="sea ice area fraction" units="%"/>
	</load>
	<load>
	  <netcdf variable_name="hs"/>
	  <wdb name="sea surface wave significant height" units="m"/>
	</load>
	<load>
	  <netcdf variable_name="temperature">
	    <dimension name="depth" value="3" />
	  </netcdf>
	  <wdb name="sea water temperature" units="K">
	    <level name="depth" value="3"/>
	  </wdb>
	</load>
	<load>
	  <netcdf variable_name="thq"/>
	  <wdb name="sea surface wave to direction" units="degree"/>
	</load>
	<load>
	  <netcdf variable_name="u">
	    <dimension name="depth" value="3" />
	  </netcdf>
	  <wdb name="sea water x velocity" units="m/s">
	    <level name="depth" value="3"/>
	  </wdb>
	</load>
	<load>
	  <netcdf variable_name="v">
	    <dimension name="depth" value="3" />
	  </netcdf>
	  <wdb name="sea water y velocity" units="m/s">
	    <level name="depth" value="3"/>
	</wdb>
	</load>

</netcdfloadconfiguration>

=== DreadPirateRoberts-1000/wdb-netcdfload/etc/eps.netcdfload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

<load>
	<netcdf cfname="cloud_area_fraction"/>
	<wdb name="cloud area fraction"/>
</load>

<load>
	<netcdf cfname="y_wind_10m"/>
	<wdb name="y wind"/>
</load>

<load>
	<netcdf cfname="x_wind_10m"/>
	<wdb name="x wind"/>
</load>

<load>
	<netcdf cfname="air_temperature_2m"/>
	<wdb name="air temperature"/>
</load>

<load>
	<netcdf cfname="precipitation_amount_acc"/>
	<wdb name="lwe thickness of precipitation amount" scale="0.001" validfrom="referencetime"/>
</load>

<load>
	<netcdf cfname="sea_level_pressure"/>
	<wdb name="air pressure at sea level"/>
</load>

<load>
	<netcdf cfname="geopotential_surface"/>
	<wdb name="geopotential"/>
</load>
	
</netcdfloadconfiguration>

=== DreadPirateRoberts-1000/wdb-netcdfload/etc/default.netcdfload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

	<!-- KEEP THIS ALPHABETICALLY ORDERED ON NETCDF VARIABLE NAME! -->

	<load>
		<netcdf variable_name="air_pressure_at_sea_level"/>
		<wdb name="air pressure at sea level" units="Pa"/>
	</load>
	<load>
		<netcdf variable_name="air_temperature_2m"/>
		<wdb name="air temperature" units="K">
			<level name="height above ground" value="2" />
		</wdb>
	</load>
        <load>
                <netcdf variable_name="air_temperature_2m_max6h" />
                <wdb name="max air temperature" units="K" validfrom="validTime - 6 hours"/>
	</load>
        <load>
                <netcdf variable_name="air_temperature_2m_min6h" />
                <wdb name="min air temperature" units="K" validfrom="validTime - 6 hours"/>
        </load>
	<load>
		<netcdf variable_name="altitude" />
		<wdb name="altitude" units="m" validfrom="-infinity" validto="infinity"/>
	</load>
	<load>
		<netcdf variable_name="cloud_area_fraction"/>
		<wdb name="cloud area fraction" units="%"/>
	</load>
	<load>
		<netcdf variable_name="dew_point_temperature_2m"/>
		<wdb name="dew point temperature" units="K">
			<level name="height above ground" value="2" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="fog_area_fraction"/>
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="1000"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="high_type_cloud_area_fraction" />
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="300"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="land_area_fraction"/>
		<wdb name="land area fraction" units="%" validfrom="-infinity" validto="infinity"/>
	</load>
	<load>
		<netcdf variable_name="low_type_cloud_area_fraction" />
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="850"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="lwe_precipitation_rate" />
		<wdb name="lwe precipitation rate" units="mm/h"/>
	</load>
	<load>
		<netcdf variable_name="medium_type_cloud_area_fraction" />
		<wdb name="cloud area fraction in atmosphere layer" units="%">
			<level name="atmosphere sigma coordinate" value="500"/>
		</wdb>
	</load>
	<load>
		<netcdf variable_name="precipitation_amount_acc"/>
		<wdb name="precipitation amount" units="kg/m2" alternativeunitconversion="mm" validfrom="referencetime"/>
	</load>
	<load>
		<netcdf variable_name="precipitation_amount_high_estimate"/>
		<wdb name="high estimate of precipitation amount" units="kg/m2" alternativeunitconversion="mm" validfrom="validtime - 1 hours"/>
	</load>
	<load>
		<netcdf variable_name="precipitation_amount_low_estimate"/>
		<wdb name="low estimate of precipitation amount" units="kg/m2" alternativeunitconversion="mm" validfrom="validtime - 1 hours"/>
	</load>
	<load>
		<netcdf variable_name="precipitation_amount_middle_estimate"/>
		<wdb name="middle estimate of precipitation amount" units="kg/m2" alternativeunitconversion="mm" validfrom="validtime - 1 hours"/>
	</load>
	<load>
		<netcdf variable_name="precipitation_amount_prob_low"/>
		<wdb name="probability of precipitation" units="%" validfrom="validtime - 1 hours"/>
	</load>
	<load>
		<netcdf variable_name="relative_humidity_2m"/>
		<wdb name="relative humidity" units="%" >
			<level name="height above ground" value="2" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="surface_geopotential"/>
		<wdb name="geopotential height" units="geopotential meters"  validfrom="-infinity" validto="infinity"/>
	</load>
	<load>
		<netcdf variable_name="thunderstorm_index_combined"/>
		<wdb name="thunderstorm probability" units="%"/>
	</load>
	<load>
		<netcdf variable_name="wind_speed_of_gust"/>
		<wdb units="m/s" name="wind speed of gust"></wdb>
	</load>
	<load>
		<netcdf variable_name="x_wind_10m"/>
		<wdb name="x wind" units="m/s">
			<level name="height above ground" value="10" />
		</wdb>
	</load>
	<load>
		<netcdf variable_name="y_wind_10m"/>
		<wdb name="y wind" units="m/s">
			<level name="height above ground" value="10" />
		</wdb>
	</load>

</netcdfloadconfiguration>

=== DreadPirateRoberts-1000/wdb-netcdfload/etc/eps2probandltf.netcdfload.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

	<load>
		<netcdf cfname="weather_symbol" />
		<wdb name="yr weather symbol" validfrom="validTime - 6 hours" />
	</load>
	<load>
		<netcdf cfname="weather_symbol_confidence" />
		<wdb name="probability of yr weather symbol" validfrom="validTime - 6 hours" />
	</load>

	<load>
		<netcdf cfname="air_temperature" />
		<wdb name="air temperature" />
	</load>
	<load>
		<netcdf cfname="air_temperature_percentiles">
			<dimension name="percentile" value="0.1" />
		</netcdf>
		<wdb name="10th percentile of air temperature" />
	</load>
	<load>
		<netcdf cfname="air_temperature_percentiles">
			<dimension name="percentile" value="0.25" />
		</netcdf>
		<wdb name="25th percentile of air temperature" />
	</load>
	<load>
		<netcdf cfname="air_temperature_percentiles">
			<dimension name="percentile" value="0.5" />
		</netcdf>
		<wdb name="50th percentile of air temperature" />
	</load>
	<load>
		<netcdf cfname="air_temperature_percentiles">
			<dimension name="percentile" value="0.75" />
		</netcdf>
		<wdb name="75th percentile of air temperature" />
	</load>
	<load>
		<netcdf cfname="air_temperature_percentiles">
			<dimension name="percentile" value="0.9" />
		</netcdf>
		<wdb name="90th percentile of air temperature" />
	</load>
	<load>
		<netcdf cfname="air_temperature_confidence">
			<dimension name="interval_of_air_temperature" value="1.5"/>
		</netcdf>
		<wdb name="probability of air temperature +/-1.5" />
	</load>
	<load>
		<netcdf cfname="air_temperature_confidence">
			<dimension name="interval_of_air_temperature" value="2.5"/>
		</netcdf>
		<wdb name="probability of air temperature +/-2.5" />
	</load>

	<load>
		<netcdf cfname="x_wind"/>
		<wdb name="x wind"/>
	</load>
	<load>
		<netcdf cfname="y_wind"/>
		<wdb name="y wind"/>
	</load>
	<load>
		<netcdf cfname="wind_speed_confidence"/>
		<wdb name="probability of wind speed"/>
	</load>

	<load>
		<netcdf cfname="precipitation_amount"/>
		<wdb name="lwe thickness of precipitation amount" scale="0.001" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_percentiles">
			<dimension name="percentile" value="0.1"/>
		</netcdf>
		<wdb name="10th percentile of precipitation amount" scale="0.001" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_percentiles">
			<dimension name="percentile" value="0.25"/>
		</netcdf>
		<wdb name="25th percentile of precipitation amount" scale="0.001" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_percentiles">
			<dimension name="percentile" value="0.5"/>
		</netcdf>
		<wdb name="50th percentile of precipitation amount" scale="0.001" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_percentiles">
			<dimension name="percentile" value="0.75"/>
		</netcdf>
		<wdb name="75th percentile of precipitation amount" scale="0.001" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_percentiles">
			<dimension name="percentile" value="0.9"/>
		</netcdf>
		<wdb name="90th percentile of precipitation amount" scale="0.001" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_limit_confidence">
			<dimension name="precipitation_limit" value="0.1"/>
		</netcdf>
		<wdb name="probability of precipitation >0.1mm" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_limit_confidence">
			<dimension name="precipitation_limit" value="0.2"/>
		</netcdf>
		<wdb name="probability of precipitation >0.2mm" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_limit_confidence">
			<dimension name="precipitation_limit" value="0.5"/>
		</netcdf>
		<wdb name="probability of precipitation >0.5mm" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_limit_confidence">
			<dimension name="precipitation_limit" value="1"/>
		</netcdf>
		<wdb name="probability of precipitation >1.0mm" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_limit_confidence">
			<dimension name="precipitation_limit" value="2"/>
		</netcdf>
		<wdb name="probability of precipitation >2.0mm" validfrom="validtime - 6 hours"/>
	</load>
	<load>
		<netcdf cfname="precipitation_limit_confidence">
			<dimension name="precipitation_limit" value="5"/>
		</netcdf>
		<wdb name="probability of precipitation >5.0mm" validfrom="validtime - 6 hours"/>
	</load>

	<load>
		<netcdf cfname="sea_level_pressure"/>
		<wdb name="air pressure at sea level"/>
	</load>

</netcdfloadconfiguration>

=== DreadPirateRoberts-1000/wdb-netcdfload/etc/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<netcdfloadconfiguration xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="netcdfLoad.configuration.xsd">

	<axis>
		<netcdf cfname="pressure" />
		<wdb name="air pressure" units="hPa"/>
	</axis>

         <load>
		<netcdf cfname="precipitation_percentiles">
			<dimension name="percentile" value="0.25"/>
		</netcdf>
		<wdb name="25th percentile of precipitation amount" scale="0.001" validfrom="validtime - 6 hours" units="kg m2"/>
	</load>

	<load>
		<netcdf cfname="geopotential_height">
		    <dimension name="pressure" value="10" />
		    <dimension name="pressure" value="30" />
		</netcdf>
		<wdb name="geopotential height" units="m"/>
	</load>

	<load>
		<netcdf cfname="air_potential_temperature">
                    <dimension name="pressure" value="10" />
		</netcdf>
		<wdb name="air temperature" units="K"/>
	</load>

	<load>
		<netcdf cfname="x_wind">
                    <dimension name="pressure" value="10" />
		</netcdf>
		<wdb name="x wind on 10" units="m/s"/>
	</load>

	<load>
		<netcdf cfname="x_wind">
                    <dimension name="pressure" value="30" />
		</netcdf>
		<wdb name="x wind on 30" units="m/s"/>
	</load>

	<load>
		<netcdf cfname="y_wind">
                    <dimension name="pressure" value="!10" />
		</netcdf>
		<wdb name="y wind" units="m/s"/>
	</load>
</netcdfloadconfiguration>
